{% set name = "zipp" %}
{% set version = "3.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a07157588a12518c9d4034df3fbbee09c814741a33ff63c05fa29d26a2404166

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=56
    - wheel
    # Add upper bound to get around circular dependency
    # zipp->setuptools_scm->importlib_metadata->zipp
    - setuptools_scm >=3.4.1,<7
    - toml
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  requires:
    - pip
    # this is a downstream that has a version requirement on zipp
    - importlib_metadata
    - jaraco.itertools
    - jaraco.test
    - jaraco.functools
    - more-itertools
    - python {{ python_min }}
  imports:
    - zipp
  commands:
    - python -m unittest tests/test_path.py
    - pip check

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  doc_url: https://zipp.readthedocs.io/en/latest
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
